# Generated by Django 3.1.3 on 2020-12-18 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201218_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entrydate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
