# Generated by Django 3.1.3 on 2020-12-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201219_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message1',
            new_name='message',
        ),
    ]
